/**
 * Comprehensive, strictly alphabetically sorted list of all 28 States and 8 Union Territories in India
 * Standardized for MediArca clinical locations and geographic filtering
 */
export const INDIAN_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
] as const;

export type IndianState = (typeof INDIAN_STATES)[number];

const STATE_ALIASES: Record<string, string> = {
  'delhi ncr': 'Delhi',
  'nct of delhi': 'Delhi',
  'national capital territory of delhi': 'Delhi',
  'new delhi': 'Delhi',
  'orissa': 'Odisha',
  'pondicherry': 'Puducherry',
  'uttaranchal': 'Uttarakhand',
  'jammu & kashmir': 'Jammu and Kashmir',
  'j&k': 'Jammu and Kashmir',
  'andaman & nicobar': 'Andaman and Nicobar Islands',
  'andaman and nicobar': 'Andaman and Nicobar Islands',
  'dadra & nagar haveli': 'Dadra and Nagar Haveli and Daman and Diu',
  'daman & diu': 'Dadra and Nagar Haveli and Daman and Diu',
  'daman and diu': 'Dadra and Nagar Haveli and Daman and Diu',
  'dadra and nagar haveli': 'Dadra and Nagar Haveli and Daman and Diu',
};

/**
 * Standardized dictionary of major cities, district headquarters, and urban centers
 * for all 36 Indian States and Union Territories.
 * Every list is strictly sorted alphabetically (A-Z).
 */
export const INDIAN_CITIES_BY_STATE: Record<IndianState, readonly string[]> = {
  'Andaman and Nicobar Islands': [
    'Bambooflat',
    'Campbell Bay',
    'Car Nicobar',
    'Diglipur',
    'Garacharma',
    'Hut Bay',
    'Mayabunder',
    'Port Blair',
    'Prothrapur',
    'Rangat',
  ],
  'Andhra Pradesh': [
    'Adoni',
    'Amalapuram',
    'Anantapur',
    'Bapatla',
    'Bhimavaram',
    'Chilakaluripet',
    'Chittoor',
    'Dharmavaram',
    'Eluru',
    'Gudivada',
    'Guntakal',
    'Guntur',
    'Hindupur',
    'Kadapa',
    'Kakinada',
    'Kavali',
    'Kurnool',
    'Machilipatnam',
    'Madanapalle',
    'Mangalagiri',
    'Markapur',
    'Nandyal',
    'Narasaraopet',
    'Nellore',
    'Ongole',
    'Palakollu',
    'Proddatur',
    'Rajamahendravaram',
    'Rayachoti',
    'Repalle',
    'Sattenapalle',
    'Srikakulam',
    'Tadepalligudem',
    'Tadipatri',
    'Tenali',
    'Tirupati',
    'Vijayawada',
    'Visakhapatnam',
    'Vizianagaram',
    'Yemmiganur',
  ],
  'Arunachal Pradesh': [
    'Aalo',
    'Anini',
    'Basar',
    'Boleng',
    'Bomdila',
    'Changlang',
    'Daporijo',
    'Hawai',
    'Itanagar',
    'Khonsa',
    'Koloriang',
    'Longding',
    'Naharlagun',
    'Namsai',
    'Pasighat',
    'Raga',
    'Roing',
    'Seppa',
    'Tawang',
    'Tezu',
    'Yingkiong',
    'Ziro',
  ],
  'Assam': [
    'Barpeta',
    'Barpeta Road',
    'Biswanath Chariali',
    'Bongaigaon',
    'Dhemaji',
    'Dhubri',
    'Dibrugarh',
    'Digboi',
    'Diphu',
    'Duliajan',
    'Goalpara',
    'Golaghat',
    'Guwahati',
    'Haflong',
    'Hailakandi',
    'Hojai',
    'Jorhat',
    'Karimganj',
    'Kokrajhar',
    'Lumding',
    'Mangaldai',
    'Margherita',
    'Morigaon',
    'Nagaon',
    'Nalbari',
    'North Lakhimpur',
    'Rangia',
    'Silchar',
    'Sivasagar',
    'Sonari',
    'Tezpur',
    'Tinsukia',
  ],
  'Bihar': [
    'Araria',
    'Arrah',
    'Aurangabad',
    'Bagaha',
    'Banka',
    'Begusarai',
    'Bettiah',
    'Bhabua',
    'Bhagalpur',
    'Bihar Sharif',
    'Buxar',
    'Chhapra',
    'Danapur',
    'Darbhanga',
    'Dehri',
    'Gaya',
    'Gopalganj',
    'Hajipur',
    'Jamalpur',
    'Jamui',
    'Jehanabad',
    'Katihar',
    'Khagaria',
    'Kishanganj',
    'Lakhisarai',
    'Madhepura',
    'Madhubani',
    'Motihari',
    'Munger',
    'Muzaffarpur',
    'Nawada',
    'Patna',
    'Purnia',
    'Saharsa',
    'Samastipur',
    'Sasaram',
    'Sheikhpura',
    'Sheohar',
    'Sitamarhi',
    'Siwan',
    'Supaul',
  ],
  'Chandigarh': [
    'Chandigarh',
  ],
  'Chhattisgarh': [
    'Ambikapur',
    'Balod',
    'Balrampur',
    'Bemetara',
    'Bhatapara',
    'Bhilai',
    'Bijapur',
    'Bilaspur',
    'Champa',
    'Dantewada',
    'Dhamtari',
    'Durg',
    'Gariaband',
    'Gaurela-Pendra-Marwahi',
    'Jagdalpur',
    'Jashpur',
    'Kanker',
    'Kawardha',
    'Khairagarh',
    'Kondagaon',
    'Korba',
    'Mahasamund',
    'Manendragarh',
    'Mungeli',
    'Narayanpur',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
    'Sakti',
    'Sarangarh',
    'Sukma',
    'Surajpur',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Amli',
    'Dadra',
    'Daman',
    'Diu',
    'Naroli',
    'Silvassa',
  ],
  'Delhi': [
    'Central Delhi',
    'Chandni Chowk',
    'Civil Lines',
    'Connaught Place',
    'Dwarka',
    'East Delhi',
    'Hauz Khas',
    'Janakpuri',
    'Karol Bagh',
    'Lajpat Nagar',
    'Laxmi Nagar',
    'Mayur Vihar',
    'Model Town',
    'New Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'Pitampura',
    'Punjabi Bagh',
    'Rohini',
    'Saket',
    'Shahdara',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'Vasant Kunj',
    'West Delhi',
  ],
  'Goa': [
    'Benaulim',
    'Bicholim',
    'Calangute',
    'Canacona',
    'Candolim',
    'Colva',
    'Cuncolim',
    'Curchorem',
    'Mapusa',
    'Margao',
    'Panaji',
    'Pernem',
    'Ponda',
    'Porvorim',
    'Quepem',
    'Sanguem',
    'Sanquelim',
    'Valpoi',
    'Vasco da Gama',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Ahwa',
    'Amreli',
    'Anand',
    'Bharuch',
    'Bhavnagar',
    'Bhuj',
    'Botad',
    'Chhota Udaipur',
    'Dahod',
    'Deesa',
    'Gandhidham',
    'Gandhinagar',
    'Godhra',
    'Gondal',
    'Himatnagar',
    'Jamnagar',
    'Jetpur',
    'Junagadh',
    'Kalol',
    'Lunawada',
    'Mehsana',
    'Modasa',
    'Morbi',
    'Nadiad',
    'Navsari',
    'Palanpur',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Rajpipla',
    'Surat',
    'Surendranagar',
    'Vadodara',
    'Valsad',
    'Vapi',
    'Veraval',
    'Vyara',
  ],
  'Haryana': [
    'Ambala',
    'Bahadurgarh',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gohana',
    'Gurugram',
    'Hansi',
    'Hisar',
    'Jagadhri',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Mandi Dabwali',
    'Narnaul',
    'Narwana',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Pehowa',
    'Rewari',
    'Rohtak',
    'Shahbad',
    'Sirsa',
    'Sonipat',
    'Thanesar',
    'Tohana',
    'Yamunanagar',
  ],
  'Himachal Pradesh': [
    'Baddi',
    'Bilaspur',
    'Chamba',
    'Dharamshala',
    'Hamirpur',
    'Joginder Nagar',
    'Kangra',
    'Kaza',
    'Keylong',
    'Kullu',
    'Manali',
    'Mandi',
    'Nahan',
    'Nalagarh',
    'Palampur',
    'Paonta Sahib',
    'Parwanoo',
    'Reckong Peo',
    'Shimla',
    'Solan',
    'Sundernagar',
    'Una',
  ],
  'Jammu and Kashmir': [
    'Akhnoor',
    'Anantnag',
    'Bandipora',
    'Baramulla',
    'Bijbehara',
    'Budgam',
    'Doda',
    'Ganderbal',
    'Gulmarg',
    'Jammu',
    'Kathua',
    'Katra',
    'Kishtwar',
    'Kulgam',
    'Kupwara',
    'Pahalgam',
    'Poonch',
    'Pulwama',
    'Rajouri',
    'Ramban',
    'Reasi',
    'Samba',
    'Shopian',
    'Sopore',
    'Srinagar',
    'Udhampur',
  ],
  'Jharkhand': [
    'Bokaro Steel City',
    'Chaibasa',
    'Chakradharpur',
    'Chatra',
    'Chirkunda',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'Giridih',
    'Godda',
    'Gumla',
    'Hazaribagh',
    'Jamshedpur',
    'Jamtara',
    'Khunti',
    'Koderma',
    'Latehar',
    'Lohardaga',
    'Madhupur',
    'Medininagar',
    'Pakur',
    'Phusro',
    'Ramgarh',
    'Ranchi',
    'Sahibganj',
    'Saraikela',
    'Simdega',
  ],
  'Karnataka': [
    'Bagalkote',
    'Ballari',
    'Belagavi',
    'Bengaluru',
    'Bhadravati',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapura',
    'Chikkamagaluru',
    'Chitradurga',
    'Davanagere',
    'Gadag-Betageri',
    'Gangavathi',
    'Hassan',
    'Haveri',
    'Hosapete',
    'Hubballi-Dharwad',
    'Kalaburagi',
    'Karwar',
    'Kolar',
    'Koppal',
    'Madikeri',
    'Mandya',
    'Mangaluru',
    'Mysuru',
    'Raichur',
    'Ramanagara',
    'Ranebennur',
    'Robertsonpet',
    'Shivamogga',
    'Sirsi',
    'Tumakuru',
    'Udupi',
    'Vijayapura',
    'Yadgir',
  ],
  'Kerala': [
    'Alappuzha',
    'Chalakudy',
    'Changanassery',
    'Cherthala',
    'Idukki',
    'Kanhangad',
    'Kannur',
    'Kasaragod',
    'Kayamkulam',
    'Kochi',
    'Kodungallur',
    'Kollam',
    'Kothamangalam',
    'Kottayam',
    'Kozhikode',
    'Kunnamkulam',
    'Malappuram',
    'Manjeri',
    'Nedumangad',
    'Palakkad',
    'Pathanamthitta',
    'Payyanur',
    'Perinthalmanna',
    'Ponnani',
    'Thalassery',
    'Thiruvananthapuram',
    'Thrissur',
    'Tirur',
    'Vatakara',
    'Wayanad',
  ],
  'Ladakh': [
    'Diskit',
    'Dras',
    'Kargil',
    'Khalatse',
    'Leh',
    'Nyoma',
    'Padum',
    'Sankoo',
  ],
  'Lakshadweep': [
    'Agatti',
    'Amini',
    'Andrott',
    'Bitra',
    'Chetlat',
    'Kadmat',
    'Kalpeni',
    'Kavaratti',
    'Kiltan',
    'Minicoy',
  ],
  'Madhya Pradesh': [
    'Agar Malwa',
    'Alirajpur',
    'Anuppur',
    'Ashoknagar',
    'Balaghat',
    'Barwani',
    'Betul',
    'Bhind',
    'Bhopal',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dindori',
    'Guna',
    'Gwalior',
    'Harda',
    'Hoshangabad',
    'Indore',
    'Itarsi',
    'Jabalpur',
    'Jhabua',
    'Khandwa',
    'Khargone',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Murwara',
    'Nagda',
    'Narsinghpur',
    'Neemuch',
    'Niwari',
    'Panna',
    'Pithampur',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Sidhi',
    'Singrauli',
    'Tikamgarh',
    'Ujjain',
    'Umaria',
    'Vidisha',
  ],
  'Maharashtra': [
    'Achalpur',
    'Ahmednagar',
    'Akola',
    'Ambarnath',
    'Amravati',
    'Barshi',
    'Beed',
    'Bhandara',
    'Bhiwandi',
    'Bhusawal',
    'Buldhana',
    'Chandrapur',
    'Chhatrapati Sambhajinagar',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Ichalkaranji',
    'Jalgaon',
    'Jalna',
    'Kalyan-Dombivli',
    'Kolhapur',
    'Latur',
    'Malegaon',
    'Mira-Bhayandar',
    'Mumbai',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Navi Mumbai',
    'Osmanabad',
    'Palghar',
    'Panvel',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Ulhasnagar',
    'Vasai-Virar',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],
  'Manipur': [
    'Bishnupur',
    'Chandel',
    'Churachandpur',
    'Imphal',
    'Jiribam',
    'Kakching',
    'Kamjong',
    'Kangpokpi',
    'Noney',
    'Pherzawl',
    'Senapati',
    'Tamenglong',
    'Tengnoupal',
    'Thoubal',
    'Ukhrul',
  ],
  'Meghalaya': [
    'Baghmara',
    'Cherrapunji',
    'Jowai',
    'Khliehriat',
    'Mairang',
    'Mawkyrwat',
    'Nongpoh',
    'Nongstoin',
    'Resubelpara',
    'Shillong',
    'Tura',
    'Williamnagar',
  ],
  'Mizoram': [
    'Aizawl',
    'Champhai',
    'Hnahthial',
    'Khawzawl',
    'Kolasib',
    'Lawngtlai',
    'Lunglei',
    'Mamit',
    'Saiha',
    'Saitual',
    'Serchhip',
  ],
  'Nagaland': [
    'Chumoukedima',
    'Dimapur',
    'Kiphire',
    'Kohima',
    'Longleng',
    'Mokokchung',
    'Mon',
    'Niuland',
    'Noklak',
    'Peren',
    'Phek',
    'Shamator',
    'Tseminyu',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],
  'Odisha': [
    'Angul',
    'Balasore',
    'Bargarh',
    'Baripada',
    'Berhampur',
    'Bhadrak',
    'Bhawanipatna',
    'Bhubaneswar',
    'Bolangir',
    'Boudh',
    'Cuttack',
    'Deogarh',
    'Dhenkanal',
    'Gajapati',
    'Ganjam',
    'Jagatsinghpur',
    'Jajpur',
    'Jatani',
    'Jeypore',
    'Jharsuguda',
    'Kandhamal',
    'Kendrapara',
    'Kendujhar',
    'Khordha',
    'Koraput',
    'Malkangiri',
    'Nabarangpur',
    'Nayagarh',
    'Nuapada',
    'Paradip',
    'Puri',
    'Rayagada',
    'Rourkela',
    'Sambalpur',
    'Subarnapur',
    'Sunabeda',
    'Talcher',
  ],
  'Puducherry': [
    'Karaikal',
    'Mahe',
    'Ozhukarai',
    'Puducherry',
    'Yanam',
  ],
  'Punjab': [
    'Abohar',
    'Amritsar',
    'Barnala',
    'Batala',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Fazilka',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Khanna',
    'Ludhiana',
    'Malerkotla',
    'Mansa',
    'Moga',
    'Mohali',
    'Muktsar',
    'Nawanshahr',
    'Pathankot',
    'Patiala',
    'Phagwara',
    'Rajpura',
    'Rupnagar',
    'Sangrur',
    'Tarn Taran',
  ],
  'Rajasthan': [
    'Ajmer',
    'Alwar',
    'Balotra',
    'Banswara',
    'Baran',
    'Barmer',
    'Beawar',
    'Bharatpur',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Chittorgarh',
    'Churu',
    'Dausa',
    'Dholpur',
    'Didwana',
    'Dungarpur',
    'Hanumangarh',
    'Jaipur',
    'Jaisalmer',
    'Jalore',
    'Jhalawar',
    'Jhunjhunu',
    'Jodhpur',
    'Kishangarh',
    'Kota',
    'Kotputli',
    'Nagaur',
    'Neem Ka Thana',
    'Pali',
    'Phalodi',
    'Pratapgarh',
    'Rajsamand',
    'Salumbar',
    'Sanchore',
    'Sawai Madhopur',
    'Sikar',
    'Sirohi',
    'Sri Ganganagar',
    'Tonk',
    'Udaipur',
  ],
  'Sikkim': [
    'Gangtok',
    'Geyzing',
    'Jorethang',
    'Mangan',
    'Namchi',
    'Nayabazar',
    'Pakyong',
    'Rangpo',
    'Ravangla',
    'Singtam',
    'Soreng',
  ],
  'Tamil Nadu': [
    'Ambur',
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Gudiyatham',
    'Hosur',
    'Kallakurichi',
    'Kancheepuram',
    'Karaikkudi',
    'Karur',
    'Krishnagiri',
    'Kumarapalayam',
    'Kumbakonam',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Nagercoil',
    'Namakkal',
    'Neyveli',
    'Paramakudi',
    'Perambalur',
    'Pollachi',
    'Pudukkottai',
    'Rajapalayam',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivakasi',
    'Tenkasi',
    'Thanjavur',
    'Thoothukudi',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Tiruvannamalai',
    'Udhagamandalam',
    'Vaniyambadi',
    'Vellore',
    'Viluppuram',
  ],
  'Telangana': [
    'Adilabad',
    'Asifabad',
    'Bellampalli',
    'Bhongir',
    'Bhupalpally',
    'Gadwal',
    'Hyderabad',
    'Jagtial',
    'Jangaon',
    'Kamareddy',
    'Karimnagar',
    'Khammam',
    'Kothagudem',
    'Mahbubnagar',
    'Mancherial',
    'Medak',
    'Miryalaguda',
    'Mulugu',
    'Nagarkurnool',
    'Nalgonda',
    'Narayanpet',
    'Nirmal',
    'Nizamabad',
    'Ramagundam',
    'Sangareddy',
    'Siddipet',
    'Sircilla',
    'Suryapet',
    'Vikarabad',
    'Wanaparthy',
    'Warangal',
  ],
  'Tripura': [
    'Agartala',
    'Ambassa',
    'Belonia',
    'Bishalgarh',
    'Dharmanagar',
    'Kailashahar',
    'Khowai',
    'Kumarghat',
    'Melaghar',
    'Ranirbazar',
    'Sabroom',
    'Santirbazar',
    'Sonamura',
    'Teliamura',
    'Udaipur',
  ],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Amethi',
    'Amroha',
    'Auraiya',
    'Ayodhya',
    'Azamgarh',
    'Baghpat',
    'Bahraich',
    'Ballia',
    'Balrampur',
    'Banda',
    'Barabanki',
    'Bareilly',
    'Basti',
    'Bhadohi',
    'Bijnor',
    'Bulandshahr',
    'Chandauli',
    'Chitrakoot',
    'Deoria',
    'Etawah',
    'Farrukhabad',
    'Fatehpur',
    'Firozabad',
    'Ghaziabad',
    'Ghazipur',
    'Gonda',
    'Gorakhpur',
    'Greater Noida',
    'Hamirpur',
    'Hapur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur',
    'Kasganj',
    'Kaushambi',
    'Kushinagar',
    'Lakhimpur',
    'Lalitpur',
    'Lucknow',
    'Maharajganj',
    'Mahoba',
    'Mainpuri',
    'Mathura',
    'Mau',
    'Meerut',
    'Mirzapur',
    'Modinagar',
    'Moradabad',
    'Muzaffarnagar',
    'Noida',
    'Pilibhit',
    'Prayagraj',
    'Raebareli',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Sant Kabir Nagar',
    'Shahjahanpur',
    'Shamli',
    'Shravasti',
    'Siddharthnagar',
    'Sitapur',
    'Sonbhadra',
    'Sultanpur',
    'Unnao',
    'Varanasi',
  ],
  'Uttarakhand': [
    'Almora',
    'Bageshwar',
    'Chamoli',
    'Champawat',
    'Dehradun',
    'Haldwani',
    'Haridwar',
    'Kashipur',
    'Kichha',
    'Kotdwar',
    'Manglaur',
    'Mussoorie',
    'Nainital',
    'Pauri',
    'Pithoragarh',
    'Ramnagar',
    'Ranikhet',
    'Rishikesh',
    'Roorkee',
    'Rudraprayag',
    'Rudrapur',
    'Sitarganj',
    'Tehri',
    'Uttarkashi',
    'Vikas Nagar',
  ],
  'West Bengal': [
    'Alipurduar',
    'Asansol',
    'Baharampur',
    'Balurghat',
    'Bankura',
    'Barasat',
    'Bardhaman',
    'Barrackpore',
    'Basirhat',
    'Bolpur',
    'Bongaon',
    'Cooch Behar',
    'Dankuni',
    'Darjeeling',
    'Dhulian',
    'Diamond Harbour',
    'Durgapur',
    'Habra',
    'Haldia',
    'Howrah',
    'Jalpaiguri',
    'Jangipur',
    'Jhargram',
    'Kalimpong',
    'Kalyani',
    'Kharagpur',
    'Kolkata',
    'Krishnanagar',
    'Malda',
    'Midnapore',
    'Nabadwip',
    'Purulia',
    'Raiganj',
    'Ranaghat',
    'Shantipur',
    'Siliguri',
    'Suri',
    'Tamluk',
  ],
};

export const normalizeIndianState = (state: string): string => {
  if (!state || typeof state !== 'string') return '';
  const trimmed = state.trim();
  const lower = trimmed.toLowerCase();
  if (STATE_ALIASES[lower]) return STATE_ALIASES[lower];
  const matched = INDIAN_STATES.find((s) => s.toLowerCase() === lower);
  return matched || trimmed;
};

export const isValidIndianState = (state: string): boolean => {
  if (!state || typeof state !== 'string') return false;
  const normalized = normalizeIndianState(state).toLowerCase();
  return INDIAN_STATES.some((s) => s.toLowerCase() === normalized);
};

/**
 * Returns strictly alphabetically sorted cities for the specified Indian state.
 * Gracefully handles state normalization and alias matching.
 */
export const getCitiesForState = (state: string): string[] => {
  if (!state || typeof state !== 'string') return [];
  const normalized = normalizeIndianState(state);
  const cities = INDIAN_CITIES_BY_STATE[normalized as IndianState];
  return cities ? [...cities] : [];
};

/**
 * Returns a deduplicated, strictly alphabetically sorted array of all cities across all Indian states and UTs.
 */
export const getAllIndianCities = (): string[] => {
  const citySet = new Set<string>();
  Object.values(INDIAN_CITIES_BY_STATE).forEach((cities) => {
    cities.forEach((c) => citySet.add(c));
  });
  return Array.from(citySet).sort((a, b) => a.localeCompare(b));
};

/**
 * Searches for cities matching a query string, optionally restricted to a specific state.
 */
export const searchIndianCities = (query: string, state?: string): string[] => {
  if (!query || typeof query !== 'string') return [];
  const q = query.trim().toLowerCase();
  const pool = state && isValidIndianState(state) ? getCitiesForState(state) : getAllIndianCities();
  return pool.filter((city) => city.toLowerCase().includes(q));
};

/**
 * Checks whether a given city belongs to a state (or exists in the national catalog).
 */
export const isValidIndianCity = (city: string, state?: string): boolean => {
  if (!city || typeof city !== 'string') return false;
  const cLower = city.trim().toLowerCase();
  if (state && isValidIndianState(state)) {
    const stateCities = getCitiesForState(state);
    return stateCities.some((c) => c.toLowerCase() === cLower);
  }
  return getAllIndianCities().some((c) => c.toLowerCase() === cLower);
};
